#!/usr/bin/env sh

_() {
  YEAR="2014"
  echo "Github Username: "
  read -r USERNAME

  echo "Github Email: "
  read -r EMAIL

  [ -z "$USERNAME" ] && exit 1
  [ -z "$EMAIL" ] && exit 1
  [ ! -d $YEAR ] && mkdir $YEAR

  cd "${YEAR}" || exit
  git init
  echo "**${YEAR}** - Generated by https://github.com/peterfranger/2014-script" \
    >README.md
  git add .
  git config user.email "${EMAIL}"
  git config user.name "${USERNAME}"
  GIT_AUTHOR_DATE="${YEAR}-01-01T18:00:00" \
    GIT_COMMITTER_DATE="${YEAR}-01-01T18:00:00" \
    git commit -m "${YEAR}"
  git remote add origin "https://github.com/${USERNAME}/${YEAR}.git"
  git branch -M main
  git push -u origin main -f
  cd ..
  rm -rf "${YEAR}"

  echo
  echo "Cool, check your profile now: https://github.com/${USERNAME}"
} && _

unset -f _
